apiVersion: v2
name: whereintheworld
description: A Helm chart for WITW

type: application

version: 0.1.0

appVersion: '0.0.1'

kubeVersion: '>= 1.21-0 <= 1.24-0'

home: https://witw.app

sources:
    - https://github.com/vglafirov/whereintheworld/tree/main/contrib/helm/whereintheworld

dependencies:
    - name: postgresql
      version: 11.x.x
      repository: https://charts.bitnami.com/bitnami
      condition: postgresql.enabled

maintainers:
    - name: vglafirov
      email: vglafirov@gmail.com
